name: Java CI with Gradle

on: 
  workflow_dispatch:
  push:
    branches: [main]
permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: Migracao-NET/pipeline_templates/.github/workflows/javagradle_build.yml@main
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    needs: build
    uses: Migracao-NET/pipeline_templates/.github/workflows/javagradle_libdeploy.yml@main