name: Java CI with Gradle

on: 
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  use-reusable-workflow: 
    uses: Migracao-NET/pipeline_templates/.github/workflows/javagradle_build.yml@main